/**
 * @file offline-popup register template
 * @author colsrch(colsrch@foxmail.com)
 * @author Ajuu Hieda(hieda@ajuu.org)
 */

/* global navigator, document */

// The registered address is the service-worker.js generated by sw-precache-webpack-plugin or the manually maintained service worker file.
if (navigator.serviceWorker) {
    navigator.serviceWorker.register('/__ServiceWorkerName__?v=__BuildVersion__').then(function () {
        navigator.serviceWorker.addEventListener('message', function (e) {

            // If service-worker.js is updated successfully, it will postMessage to the page with the content 'sw.update'.
            if (e.data === 'sw.update') {
                let themeColor = document.querySelector('meta[name=theme-color]');
                let dom = document.createElement('div');

                themeColor && (themeColor.content = '#000');

                /* eslint-disable max-len */
                dom.innerHTML = ''
                    + '<div>'
                        + '<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Colsrch/CDN/hexo-offline-popup.css">'
                        + '<div class="c-message animated animated-lento slideInRight">'
                            + '<i class=" c-message--icon c-message--success"></i>'
                            + '<div class="el-notification__group">'
                                + '<h2 class="c-message__title">System Updated</h2>'
                                + '<div class="el-notification__content">Refreshing...</div>'
                                + '<div class="c-message--close" onclick="location.reload()">×</div>'
                            + '</div>'
                        + '</div>'
                    + '</div>'
                ;
                /* eslint-enable max-len */

                document.body.appendChild(dom);
                setTimeout(function () {
                    document.getElementById('app-refresh').className += ' app-refresh-show';
                }, 16);
            }
        });
    });
}
